# Generated by Django 2.2.2 on 2019-06-08 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_product_seller_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
