# Generated by Django 2.2.2 on 2019-06-11 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190608_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronic', 'Electronic'), ('stationary', 'Stationary'), ('roomdecor', 'Room Decor'), ('vehicle', 'Vehicle'), ('job', 'Job'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
