# Generated by Django 2.2.2 on 2019-06-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190611_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='college_name',
            new_name='college',
        ),
    ]
