# Generated by Django 2.2.2 on 2019-06-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190608_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college_name',
            field=models.CharField(choices=[('nitkkr', 'NIT KURUKSHETRA'), ('thappar', 'THAPPAR , PATIALA')], default='nitkkr', max_length=20),
        ),
    ]
